In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os

In [3]:
file = 'C:/Users/cathx/repos/argoverse-api/argo_test/image_2'

In [6]:
mat = np.array([[[[4, 8], [8, 6]],[[2, 4], [4, 2]], [[1, 10], [1, 10]]], 
               [[[1, 5], [1, 5]], [[7, 3], [7, 3]], [[9, 0], [0,9]]]])

In [12]:
mat

array([[[[ 4,  8],
         [ 8,  6]],

        [[ 2,  4],
         [ 4,  2]],

        [[ 1, 10],
         [ 1, 10]]],


       [[[ 1,  5],
         [ 1,  5]],

        [[ 7,  3],
         [ 7,  3]],

        [[ 9,  0],
         [ 0,  9]]]])

In [7]:
mat.shape

(2, 3, 2, 2)

In [8]:
N, C, H, W = mat.shape

In [9]:
mat_reshaped = mat.transpose(0, 2, 3, 1).reshape(N*H*W, C)

In [10]:
mat_reshaped.shape

(8, 3)

In [11]:
mat_reshaped

array([[ 4,  2,  1],
       [ 8,  4, 10],
       [ 8,  4,  1],
       [ 6,  2, 10],
       [ 1,  7,  9],
       [ 5,  3,  0],
       [ 1,  7,  0],
       [ 5,  3,  9]])

In [14]:
mean = np.sum(mat_reshaped, axis=0)/N
batch_var = np.var(mat_reshaped, axis=0)


In [15]:
mean

array([19., 16., 20.])

In [16]:
batch_var

array([ 6.4375,  3.5   , 20.5   ])

### Using list comprehension inside a function explore

In [1]:
# corr_prob = -np.log(exp[range(num_train), y])


NameError: name 'np' is not defined