## Basics of NNs as implemented in CS231n cours

In [1]:
import numpy as np

In [2]:
# initialize the initial weights:
input_size = 1024
hidden_size = 50

x = np.random.randn(input_size, 1)
w1 = np.random.randn(input_size, hidden_size)

In [7]:
x.shape, w1.shape

((1024, 1), (1024, 50))

In [8]:
x.T.shape

(1, 1024)

In [5]:
output = np.dot(x.T, w1)

In [6]:
output

array([[-20.11085478,  35.02071891,  24.93775942,  -2.36659586,
          1.59628459, -12.78552488,  16.81440687, -39.56491769,
         18.67920104,   4.52327977, -18.92759083,  10.07248172,
         21.3956843 ,  -4.89597183,  -0.08385751, -34.31412537,
        -36.47671703, -27.8831657 ,  -7.66784477,  30.12919374,
        -61.63725311, -16.9886547 ,  -4.68246539, -17.51276998,
          3.02631494, -13.52861579,  33.15528772,  -9.84621777,
        -36.29477108,  16.3321049 ,  49.90532226, -11.48086737,
        -50.18419546, -12.96374485, -34.43132622,  -9.34524942,
         -9.56900791,  13.21988102, -39.05494091,   1.72581154,
         41.97053867, -29.58373367,  26.52288077,  32.41503974,
         29.50177845,  -0.94247411,  40.75375653,   2.01883975,
         15.09616354,   2.37649119]])

In [16]:
x = np.array([[6],
             [3],
              [4]])
w1 = np.array([[3, 4, 5, 6],
               [9, 0, 1, 2],
               [4, 7, 8, 3]])


In [21]:
x

array([[6],
       [3],
       [4]])

In [22]:
x.T

array([[6, 3, 4]])

In [17]:
x.shape, w1.shape

((3, 1), (3, 4))

In [19]:
outputs = np.dot(x.T, w1)

outputs.shape

(1, 4)

In [20]:
outputs

array([[61, 52, 65, 54]])